# Prefix key : C-t
unbind-key C-b
set-option -g prefix C-t

# Reload config file : C-r
bind-key C-r source-file ~/.tmux.conf\; display-message "[tmux] $HOME/.tmux.conf reloaded!"

bind-key C-c new-window -n 'shell'
bind-key C-W choose-window

set-window-option -g mode-keys vi
set-option -g mouse on

set-window-option -g synchronize-panes off
bind C-e \
  if-shell "tmux show-window-options synchronize-panes | grep off" \
    "set-window-option synchronize-panes on \; display-message \"[tmux] synchronize-panes on\"" \
    "set-window-option synchronize-panes off \; display-message \"[tmux] synchronize-panes off\""

# default shell
set-option -g default-shell "${SHELL}"
set -g default-command "${SHELL}"

set -g status-position top
# status line の背景色を指定する。
set-option -g status-bg "colour238"
# status line の文字色を指定する。
set-option -g status-fg "colour252"
# window-status のフォーマットを指定する。
set-window-option -g window-status-format " #I: #W #[default]"
# カレントウィンドウの window-status のフォーマットを指定する
set-window-option -g window-status-current-format "#[fg=colour255,bg=colour242,bold] #I: #W #[default]"
set -g status-right-length 100
set -g status-interval 30
set -g status-right "#(/bin/bash $HOME/.tmux/plugins/kube-tmux/kube.tmux) | IP: #(ifconfig | grep \"inet \" | grep -Fv 127.0.0.1 | awk '{print $2}') / #(curl httpbin.org/ip | jq -r '.origin' | tr -d '\"') | [#(~/date_script.sh)]"

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'nhdaly/tmux-scroll-copy-mode'
set -g @plugin 'jonmosco/kube-tmux'
run '~/.tmux/plugins/tpm/tpm'
