# Prefix key : C-e
unbind-key C-b
set-option -g prefix C-t

# Reload config file : C-r
bind-key C-r source-file ~/.tmux.conf\; display-message "[tmux] $HOME/.tmux.conf reloaded!"

bind-key C-c new-window -n 'shell'
bind-key C-W choose-window

set-window-option -g mode-keys vi
set-option -g mouse on

set-window-option -g synchronize-panes off
bind C-e \
  if-shell "tmux show-window-options synchronize-panes | grep off" \
    "set-window-option synchronize-panes on \; display-message \"[tmux] synchronize-panes on\"" \
    "set-window-option synchronize-panes off \; display-message \"[tmux] synchronize-panes off\""

set -g status-position top
set-window-option -g window-status-format " #I: #W #[default]"
set-window-option -g window-status-current-format " #I: #W #[default]"
set -g status-right-length 100
set -g status-interval 30
set -g status-right "IP: #(curl httpbin.org/ip | jq '.origin' | tr -d '\"') | [#(env LANG=C date +'%Y-%m-%d(%a) %H:%M')]"

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'seebi/tmux-colors-solarized'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'nhdaly/tmux-scroll-copy-mode'
run '~/.tmux/plugins/tpm/tpm'
